<?php

//application details
$apps[$x]['name'] = "Meta";
$apps[$x]['uuid'] = "78240306-98db-4445-a4b4-a6a22682ac58";
$apps[$x]['category'] = "";
$apps[$x]['subcategory'] = "";
$apps[$x]['version'] = "0.1";
$apps[$x]['license'] = "";
$apps[$x]['url'] = "https://developers.facebook.com/docs/whatsapp/";
$apps[$x]['description']['en-us'] = "Meta";
$apps[$x]['description']['en-gb'] = "Meta";
$apps[$x]['description']['ar-eg'] = "Meta";
$apps[$x]['description']['de-at'] = "Meta";
$apps[$x]['description']['de-ch'] = "Meta";
$apps[$x]['description']['de-de'] = "Meta";
$apps[$x]['description']['es-cl'] = "Meta";
$apps[$x]['description']['es-mx'] = "Meta";
$apps[$x]['description']['fr-ca'] = "Meta";
$apps[$x]['description']['fr-fr'] = "Meta";
$apps[$x]['description']['he-il'] = "Meta";
$apps[$x]['description']['it-it'] = "Meta";
$apps[$x]['description']['nl-nl'] = "Meta";
$apps[$x]['description']['pl-pl'] = "Meta";
$apps[$x]['description']['pt-br'] = "Meta";
$apps[$x]['description']['pt-pt'] = "Meta";
$apps[$x]['description']['ro-ro'] = "Meta";
$apps[$x]['description']['ru-ru'] = "Meta";
$apps[$x]['description']['sv-se'] = "Meta";
$apps[$x]['description']['uk-ua'] = "Meta";

//default settings
$y=0;
$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "c009b700-0908-494c-8ce2-d0b56546e818";
$apps[$x]['default_settings'][$y]['default_setting_category'] = "meta";
$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "graph_url";
$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
$apps[$x]['default_settings'][$y]['default_setting_description'] = "Base URL for graph API calls";
$y++;
$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "b1fbf550-99d0-4b99-9f0b-1f9006564bc8";
$apps[$x]['default_settings'][$y]['default_setting_category'] = "meta";
$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "api_version";
$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
$apps[$x]['default_settings'][$y]['default_setting_description'] = "Graph API version";
$y++;
$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "13fdc848-0eeb-4f8d-90a2-24450004fa0c";
$apps[$x]['default_settings'][$y]['default_setting_category'] = "meta";
$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "system_access_token";
$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
$apps[$x]['default_settings'][$y]['default_setting_description'] = "System Access Token";
$y++;
$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "af35b449-621b-4d71-bd92-3f94cd1b18d5";
$apps[$x]['default_settings'][$y]['default_setting_category'] = "meta";
$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "business_id";
$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
$apps[$x]['default_settings'][$y]['default_setting_description'] = "Meta Business Id";
$y++;
$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "fe3160c8-1f7a-4c98-ba36-5f2eccb94159";
$apps[$x]['default_settings'][$y]['default_setting_category'] = "meta";
$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "app_id";
$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
$apps[$x]['default_settings'][$y]['default_setting_description'] = "Meta App Id";

//schema details
$y = 0;
$apps[$x]['db'][$y]['table']['name'] = "v_waba";
$apps[$x]['db'][$y]['table']['parent'] = "";
$z = 0;
$apps[$x]['db'][$y]['fields'][$z]['name'] = "waba_uuid";
$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
$z++;
$apps[$x]['db'][$y]['fields'][$z]['name'] = "waba_id";
$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "bigint";
$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "integer";
$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "int";
$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
$z++;
$apps[$x]['db'][$y]['fields'][$z]['name'] = "domain_uuid";
$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_domains";
$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "domain_uuid";
$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
$z++;
$apps[$x]['db'][$y]['fields'][$z]['name'] = "insert_date";
$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'timestamptz';
$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'date';
$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'date';
$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
$z++;
$apps[$x]['db'][$y]['fields'][$z]['name'] = "insert_user";
$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
$z++;
$apps[$x]['db'][$y]['fields'][$z]['name'] = "update_date";
$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'timestamptz';
$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'date';
$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'date';
$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
$z++;
$apps[$x]['db'][$y]['fields'][$z]['name'] = "update_user";
$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";

//permission details
$y=0;
$apps[$x]['permissions'][$y]['name'] = "meta_view";
$apps[$x]['permissions'][$y]['menu']['uuid'] = "0b2315c2-d633-49e0-a081-4208373cfaa4";
$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
$apps[$x]['permissions'][$y]['groups'][] = "admin";
$y++;
$apps[$x]['permissions'][$y]['name'] = "meta_edit";
$apps[$x]['permissions'][$y]['groups'][] = "superadmin";