<?php

$text['title-agent_panel']['en-us'] = "Agent Panel";
$text['title-agent_panel']['en-gb'] = "Agent Panel";
$text['title-agent_panel']['ar-eg'] = "Agent Panel";
$text['title-agent_panel']['de-at'] = "Agent Panel";
$text['title-agent_panel']['de-ch'] = "Agent Panel";
$text['title-agent_panel']['de-de'] = "Agent Panel";
$text['title-agent_panel']['es-cl'] = "Agent Panel";
$text['title-agent_panel']['es-mx'] = "Agent Panel";
$text['title-agent_panel']['fr-ca'] = "Agent Panel";
$text['title-agent_panel']['fr-fr'] = "Agent Panel";
$text['title-agent_panel']['he-il'] = "Agent Panel";
$text['title-agent_panel']['it-it'] = "Agent Panel";
$text['title-agent_panel']['nl-nl'] = "Agent Panel";
$text['title-agent_panel']['pl-pl'] = "Agent Panel";
$text['title-agent_panel']['pt-br'] = "Agent Panel";
$text['title-agent_panel']['pt-pt'] = "Agent Panel";
$text['title-agent_panel']['ro-ro'] = "Agent Panel";
$text['title-agent_panel']['ru-ru'] = "Agent Panel";
$text['title-agent_panel']['sv-se'] = "Agent Panel";
$text['title-agent_panel']['uk-ua'] = "Agent Panel";

$text['title-phone']['en-us'] = "Phone";
$text['title-phone']['en-gb'] = "Phone";
$text['title-phone']['ar-eg'] = "Phone";
$text['title-phone']['de-at'] = "Phone";
$text['title-phone']['de-ch'] = "Phone";
$text['title-phone']['de-de'] = "Phone";
$text['title-phone']['es-cl'] = "Phone";
$text['title-phone']['es-mx'] = "Phone";
$text['title-phone']['fr-ca'] = "Phone";
$text['title-phone']['fr-fr'] = "Phone";
$text['title-phone']['he-il'] = "Phone";
$text['title-phone']['it-it'] = "Phone";
$text['title-phone']['nl-nl'] = "Phone";
$text['title-phone']['pl-pl'] = "Phone";
$text['title-phone']['pt-br'] = "Telefone";
$text['title-phone']['pt-pt'] = "Telefone";
$text['title-phone']['ro-ro'] = "Phone";
$text['title-phone']['ru-ru'] = "Phone";
$text['title-phone']['sv-se'] = "Phone";
$text['title-phone']['uk-ua'] = "Phone";

$text['title-received']['en-us'] = "Received Calls";
$text['title-received']['en-gb'] = "Received Calls";
$text['title-received']['ar-eg'] = "Received Calls";
$text['title-received']['de-at'] = "Received Calls";
$text['title-received']['de-ch'] = "Received Calls";
$text['title-received']['de-de'] = "Received Calls";
$text['title-received']['es-cl'] = "Received Calls";
$text['title-received']['es-mx'] = "Received Calls";
$text['title-received']['fr-ca'] = "Received Calls";
$text['title-received']['fr-fr'] = "Received Calls";
$text['title-received']['he-il'] = "Received Calls";
$text['title-received']['it-it'] = "Received Calls";
$text['title-received']['nl-nl'] = "Received Calls";
$text['title-received']['pl-pl'] = "Received Calls";
$text['title-received']['pt-br'] = "Chamadas Recebidas";
$text['title-received']['pt-pt'] = "Chamadas Recebidas";
$text['title-received']['ro-ro'] = "Received Calls";
$text['title-received']['ru-ru'] = "Received Calls";
$text['title-received']['sv-se'] = "Received Calls";
$text['title-received']['uk-ua'] = "Received Calls";

$text['title-missed']['en-us'] = "Missed Calls";
$text['title-missed']['en-gb'] = "Missed Calls";
$text['title-missed']['ar-eg'] = "Missed Calls";
$text['title-missed']['de-at'] = "Missed Calls";
$text['title-missed']['de-ch'] = "Missed Calls";
$text['title-missed']['de-de'] = "Missed Calls";
$text['title-missed']['es-cl'] = "Missed Calls";
$text['title-missed']['es-mx'] = "Missed Calls";
$text['title-missed']['fr-ca'] = "Missed Calls";
$text['title-missed']['fr-fr'] = "Missed Calls";
$text['title-missed']['he-il'] = "Missed Calls";
$text['title-missed']['it-it'] = "Missed Calls";
$text['title-missed']['nl-nl'] = "Missed Calls";
$text['title-missed']['pl-pl'] = "Missed Calls";
$text['title-missed']['pt-br'] = "Chamadas Perdidas";
$text['title-missed']['pt-pt'] = "Chamadas Perdidas";
$text['title-missed']['ro-ro'] = "Missed Calls";
$text['title-missed']['ru-ru'] = "Missed Calls";
$text['title-missed']['sv-se'] = "Missed Calls";
$text['title-missed']['uk-ua'] = "Missed Calls";

$text['label-name']['en-us'] = "New Contact";
$text['label-name']['en-gb'] = "New Contact";
$text['label-name']['ar-eg'] = "New Contact";
$text['label-name']['de-at'] = "New Contact";
$text['label-name']['de-ch'] = "New Contact";
$text['label-name']['de-de'] = "New Contact";
$text['label-name']['es-cl'] = "New Contact";
$text['label-name']['es-mx'] = "New Contact";
$text['label-name']['fr-ca'] = "New Contact";
$text['label-name']['fr-fr'] = "New Contact";
$text['label-name']['he-il'] = "New Contact";
$text['label-name']['it-it'] = "New Contact";
$text['label-name']['nl-nl'] = "New Contact";
$text['label-name']['pl-pl'] = "New Contact";
$text['label-name']['pt-br'] = "Novo Contato";
$text['label-name']['pt-pt'] = "Novo Contato";
$text['label-name']['ro-ro'] = "New Contact";
$text['label-name']['ru-ru'] = "New Contact";
$text['label-name']['sv-se'] = "New Contact";
$text['label-name']['uk-ua'] = "New Contact";

$text['label-direction']['en-us'] = "Direction";
$text['label-direction']['en-gb'] = "Direction";
$text['label-direction']['ar-eg'] = "";
$text['label-direction']['de-at'] = "Richtung"; //copied from de-de
$text['label-direction']['de-ch'] = "Richtung"; //copied from de-de
$text['label-direction']['de-de'] = "Richtung";
$text['label-direction']['es-cl'] = "Dirección";
$text['label-direction']['es-mx'] = "Dirección"; //copied from es-cl
$text['label-direction']['fr-ca'] = "Direction"; //copied from fr-fr
$text['label-direction']['fr-fr'] = "Direction";
$text['label-direction']['he-il'] = "";
$text['label-direction']['it-it'] = "Direzione";
$text['label-direction']['nl-nl'] = "";
$text['label-direction']['pl-pl'] = "Kierunek";
$text['label-direction']['pt-br'] = "Direção"; //copied from pt-pt
$text['label-direction']['pt-pt'] = "Direção";
$text['label-direction']['ro-ro'] = "";
$text['label-direction']['ru-ru'] = "Направление";
$text['label-direction']['sv-se'] = "Riktning";
$text['label-direction']['uk-ua'] = "";

$text['label-answered']['en-us'] = "Answered";
$text['label-answered']['en-gb'] = "Answered";
$text['label-answered']['ar-eg'] = "تم الرد";
$text['label-answered']['de-at'] = "Angenommen"; //copied from de-de
$text['label-answered']['de-ch'] = "Angenommen"; //copied from de-de
$text['label-answered']['de-de'] = "Angenommen";
$text['label-answered']['es-cl'] = "Respondido";
$text['label-answered']['es-mx'] = "Respondido"; //copied from es-cl
$text['label-answered']['fr-ca'] = "Répondu"; //copied from fr-fr
$text['label-answered']['fr-fr'] = "Répondu";
$text['label-answered']['he-il'] = "";
$text['label-answered']['it-it'] = "Risposta";
$text['label-answered']['nl-nl'] = "";
$text['label-answered']['pl-pl'] = "Odebrano";
$text['label-answered']['pt-br'] = "Atendidas"; //copied from pt-pt
$text['label-answered']['pt-pt'] = "Atendidas";
$text['label-answered']['ro-ro'] = "";
$text['label-answered']['ru-ru'] = "Отвечено";
$text['label-answered']['sv-se'] = "Besvarad";
$text['label-answered']['uk-ua'] = "відповів";

$text['label-cancelled']['en-us'] = "Cancelled";
$text['label-cancelled']['en-gb'] = "Cancelled";
$text['label-cancelled']['ar-eg'] = "ألغيت";
$text['label-cancelled']['de-at'] = "Abgebrochen"; //copied from de-de
$text['label-cancelled']['de-ch'] = "Abgebrochen"; //copied from de-de
$text['label-cancelled']['de-de'] = "Abgebrochen";
$text['label-cancelled']['es-cl'] = "Cancelado";
$text['label-cancelled']['es-mx'] = "Cancelado"; //copied from es-cl
$text['label-cancelled']['fr-ca'] = "Annulé"; //copied from fr-fr
$text['label-cancelled']['fr-fr'] = "Annulé";
$text['label-cancelled']['he-il'] = "";
$text['label-cancelled']['it-it'] = "Cancellato";
$text['label-cancelled']['nl-nl'] = "";
$text['label-cancelled']['pl-pl'] = "Odwołany";
$text['label-cancelled']['pt-br'] = "Cancelado"; //copied from pt-pt
$text['label-cancelled']['pt-pt'] = "Cancelado";
$text['label-cancelled']['ro-ro'] = "";
$text['label-cancelled']['ru-ru'] = "Отменено";
$text['label-cancelled']['sv-se'] = "Avbröts";
$text['label-cancelled']['uk-ua'] = "скасовано";

$text['label-failed']['en-us'] = "Failed";
$text['label-failed']['en-gb'] = "Failed";
$text['label-failed']['ar-eg'] = "";
$text['label-failed']['de-at'] = "Fehlgeschlagen"; //copied from de-de
$text['label-failed']['de-ch'] = "Fehlgeschlagen"; //copied from de-de
$text['label-failed']['de-de'] = "Fehlgeschlagen";
$text['label-failed']['es-cl'] = "Fracasado";
$text['label-failed']['es-mx'] = "Fracasado"; //copied from es-cl
$text['label-failed']['fr-ca'] = "Manqué"; //copied from fr-fr
$text['label-failed']['fr-fr'] = "Manqué";
$text['label-failed']['he-il'] = "";
$text['label-failed']['it-it'] = "Fallita";
$text['label-failed']['nl-nl'] = "";
$text['label-failed']['pl-pl'] = "Nie powiodło się";
$text['label-failed']['pt-br'] = "Fracassado"; //copied from pt-pt
$text['label-failed']['pt-pt'] = "Fracassado";
$text['label-failed']['ro-ro'] = "";
$text['label-failed']['ru-ru'] = "Ошибка";
$text['label-failed']['sv-se'] = "Misslyckad";
$text['label-failed']['uk-ua'] = "";

$text['label-voicemail']['en-us'] = "Voicemail";
$text['label-voicemail']['en-gb'] = "Voicemail";
$text['label-voicemail']['ar-eg'] = "";
$text['label-voicemail']['de-at'] = "Mailbox"; //copied from de-de
$text['label-voicemail']['de-ch'] = "Mailbox"; //copied from de-de
$text['label-voicemail']['de-de'] = "Mailbox";
$text['label-voicemail']['es-cl'] = "Correo de Voz";
$text['label-voicemail']['es-mx'] = "Correo de Voz"; //copied from es-cl
$text['label-voicemail']['fr-ca'] = "Messagerie vocale"; //copied from fr-fr
$text['label-voicemail']['fr-fr'] = "Messagerie vocale";
$text['label-voicemail']['he-il'] = "";
$text['label-voicemail']['it-it'] = "Casella Vocale";
$text['label-voicemail']['nl-nl'] = "";
$text['label-voicemail']['pl-pl'] = "Poczta głosowa";
$text['label-voicemail']['pt-br'] = "Correio de voz";
$text['label-voicemail']['pt-pt'] = "Correio de Voz";
$text['label-voicemail']['ro-ro'] = "";
$text['label-voicemail']['ru-ru'] = "Голосовая почта";
$text['label-voicemail']['sv-se'] = "Röstbrevlåda";
$text['label-voicemail']['uk-ua'] = "Голосова пошта";

$text['label-outbound']['en-us'] = "Outbound";
$text['label-outbound']['en-gb'] = "Outbound";
$text['label-outbound']['ar-eg'] = "";
$text['label-outbound']['de-at'] = "Ausgehend"; //copied from de-de
$text['label-outbound']['de-ch'] = "Ausgehend"; //copied from de-de
$text['label-outbound']['de-de'] = "Ausgehend";
$text['label-outbound']['es-cl'] = "Salida";
$text['label-outbound']['es-mx'] = "Salida"; //copied from es-cl
$text['label-outbound']['fr-ca'] = "Sortant"; //copied from fr-fr
$text['label-outbound']['fr-fr'] = "Sortant";
$text['label-outbound']['he-il'] = "";
$text['label-outbound']['it-it'] = "In Uscita";
$text['label-outbound']['nl-nl'] = "";
$text['label-outbound']['pl-pl'] = "Wychodzące";
$text['label-outbound']['pt-br'] = "Saída"; //copied from pt-pt
$text['label-outbound']['pt-pt'] = "Saída";
$text['label-outbound']['ro-ro'] = "";
$text['label-outbound']['ru-ru'] = "Исходящие";
$text['label-outbound']['sv-se'] = "Utgående";
$text['label-outbound']['uk-ua'] = "";

$text['label-inbound']['en-us'] = "Inbound";
$text['label-inbound']['en-gb'] = "Inbound";
$text['label-inbound']['ar-eg'] = "";
$text['label-inbound']['de-at'] = "Eingehend"; //copied from de-de
$text['label-inbound']['de-ch'] = "Eingehend"; //copied from de-de
$text['label-inbound']['de-de'] = "Eingehend";
$text['label-inbound']['es-cl'] = "Entrada";
$text['label-inbound']['es-mx'] = "Entrada"; //copied from es-cl
$text['label-inbound']['fr-ca'] = "Entrant"; //copied from fr-fr
$text['label-inbound']['fr-fr'] = "Entrant";
$text['label-inbound']['he-il'] = "";
$text['label-inbound']['it-it'] = "In Ingresso";
$text['label-inbound']['nl-nl'] = "";
$text['label-inbound']['pl-pl'] = "Przychodzące";
$text['label-inbound']['pt-br'] = "Entrada"; //copied from pt-pt
$text['label-inbound']['pt-pt'] = "Entrada";
$text['label-inbound']['ro-ro'] = "";
$text['label-inbound']['ru-ru'] = "Входящие";
$text['label-inbound']['sv-se'] = "Inkommande";
$text['label-inbound']['uk-ua'] = "Вихідний";

$text['label-local']['en-us'] = "Local";
$text['label-local']['en-gb'] = "Local";
$text['label-local']['ar-eg'] = "";
$text['label-local']['de-at'] = "Lokal"; //copied from de-de
$text['label-local']['de-ch'] = "Lokal"; //copied from de-de
$text['label-local']['de-de'] = "Lokal";
$text['label-local']['es-cl'] = "Local";
$text['label-local']['es-mx'] = "Local"; //copied from es-cl
$text['label-local']['fr-ca'] = "Local"; //copied from fr-fr
$text['label-local']['fr-fr'] = "Local";
$text['label-local']['he-il'] = "";
$text['label-local']['it-it'] = "Locale";
$text['label-local']['nl-nl'] = "";
$text['label-local']['pl-pl'] = "Lokalne";
$text['label-local']['pt-br'] = "Local"; //copied from pt-pt
$text['label-local']['pt-pt'] = "Local";
$text['label-local']['ro-ro'] = "";
$text['label-local']['ru-ru'] = "Локальный";
$text['label-local']['sv-se'] = "Lokal";
$text['label-local']['uk-ua'] = "Локальний";

$text['label-caller_id_number']['en-us'] = "Caller Number";
$text['label-caller_id_number']['en-gb'] = "Caller Number";
$text['label-caller_id_number']['ar-eg'] = "";
$text['label-caller_id_number']['de-at'] = "Anrufer Nummer"; //copied from de-de
$text['label-caller_id_number']['de-ch'] = "Anrufer Nummer"; //copied from de-de
$text['label-caller_id_number']['de-de'] = "Anrufer Nummer";
$text['label-caller_id_number']['es-cl'] = "Número CID";
$text['label-caller_id_number']['es-mx'] = "Número CID"; //copied from es-cl
$text['label-caller_id_number']['fr-ca'] = "Numéro de l'Appelant"; //copied from fr-fr
$text['label-caller_id_number']['fr-fr'] = "Numéro de l'Appelant";
$text['label-caller_id_number']['he-il'] = "";
$text['label-caller_id_number']['it-it'] = "Numero CID";
$text['label-caller_id_number']['nl-nl'] = "";
$text['label-caller_id_number']['pl-pl'] = "Prezentacja numeru dzwoniącego";
$text['label-caller_id_number']['pt-br'] = "Número de Origem"; //copied from pt-pt
$text['label-caller_id_number']['pt-pt'] = "Número CID";
$text['label-caller_id_number']['ro-ro'] = "";
$text['label-caller_id_number']['ru-ru'] = "CID номера";
$text['label-caller_id_number']['sv-se'] = "CID, Nummer";
$text['label-caller_id_number']['uk-ua'] = "CID Номер";

$text['label-destination_number']['en-us'] = "Destination";
$text['label-destination_number']['en-gb'] = "Destination";
$text['label-destination_number']['ar-eg'] = "";
$text['label-destination_number']['de-at'] = "Ziel"; //copied from de-de
$text['label-destination_number']['de-ch'] = "Ziel"; //copied from de-de
$text['label-destination_number']['de-de'] = "Ziel";
$text['label-destination_number']['es-cl'] = "Destino";
$text['label-destination_number']['es-mx'] = "Destino"; //copied from es-cl
$text['label-destination_number']['fr-ca'] = "Destination"; //copied from fr-fr
$text['label-destination_number']['fr-fr'] = "Destination";
$text['label-destination_number']['he-il'] = "";
$text['label-destination_number']['it-it'] = "Destinazione";
$text['label-destination_number']['nl-nl'] = "";
$text['label-destination_number']['pl-pl'] = "Numer docelowy";
$text['label-destination_number']['pt-br'] = "Destino final";
$text['label-destination_number']['pt-pt'] = "Destino";
$text['label-destination_number']['ro-ro'] = "";
$text['label-destination_number']['ru-ru'] = "Назначение";
$text['label-destination_number']['sv-se'] = "Destination";
$text['label-destination_number']['uk-ua'] = "Номер";

$text['label-start_stamp']['en-us'] = "Start Date/Time";
$text['label-start_stamp']['en-gb'] = "Start Date/Time";
$text['label-start_stamp']['ar-eg'] = "";
$text['label-start_stamp']['de-at'] = "Start Datum/Zeit"; //copied from de-de
$text['label-start_stamp']['de-ch'] = "Start Datum/Zeit"; //copied from de-de
$text['label-start_stamp']['de-de'] = "Start Datum/Zeit";
$text['label-start_stamp']['es-cl'] = "Fecha/Hora de Comienzo";
$text['label-start_stamp']['es-mx'] = "Fecha/Hora de Comienzo"; //copied from es-cl
$text['label-start_stamp']['fr-ca'] = "Date de Début/Heure"; //copied from fr-fr
$text['label-start_stamp']['fr-fr'] = "Date de Début/Heure";
$text['label-start_stamp']['he-il'] = "";
$text['label-start_stamp']['it-it'] = "Data/Ora Inizio";
$text['label-start_stamp']['nl-nl'] = "";
$text['label-start_stamp']['pl-pl'] = "Czas i data rozpoczęcia";
$text['label-start_stamp']['pt-br'] = "Data/Hora de inicio";
$text['label-start_stamp']['pt-pt'] = "Data/Hora de Início";
$text['label-start_stamp']['ro-ro'] = "";
$text['label-start_stamp']['ru-ru'] = "Старт Дата/Время";
$text['label-start_stamp']['sv-se'] = "Start Datum/Tid";
$text['label-start_stamp']['uk-ua'] = "";

$text['title-contacts']['en-us'] = "Contacts";
$text['title-contacts']['en-gb'] = "Contacts";
$text['title-contacts']['ar-eg'] = "";
$text['title-contacts']['de-at'] = "Kontakte"; //copied from de-de
$text['title-contacts']['de-ch'] = "Kontakte"; //copied from de-de
$text['title-contacts']['de-de'] = "Kontakte";
$text['title-contacts']['el-gr'] = "Επαφές";
$text['title-contacts']['es-cl'] = "Contactos";
$text['title-contacts']['es-mx'] = "Contactos"; //copied from es-cl
$text['title-contacts']['fr-ca'] = "Contacts"; //copied from fr-fr
$text['title-contacts']['fr-fr'] = "Contacts";
$text['title-contacts']['he-il'] = "אנשי קשר";
$text['title-contacts']['it-it'] = "Contatti";
$text['title-contacts']['nl-nl'] = "Kontacten";
$text['title-contacts']['pl-pl'] = "Kontakty";
$text['title-contacts']['pt-br'] = "Contatos";
$text['title-contacts']['pt-pt'] = "Contactos";
$text['title-contacts']['ro-ro'] = "";
$text['title-contacts']['ru-ru'] = "Контакты";
$text['title-contacts']['sv-se'] = "Kontakter";
$text['title-contacts']['uk-ua'] = "Контакти";

//CONTACT_ADD----------------------------------------------

$text['label-contact_organization']['en-us'] = "Organization";
$text['label-contact_organization']['en-gb'] = "Organization";
$text['label-contact_organization']['ar-eg'] = "";
$text['label-contact_organization']['de-at'] = "Organisation"; //copied from de-de
$text['label-contact_organization']['de-ch'] = "Organisation"; //copied from de-de
$text['label-contact_organization']['de-de'] = "Organisation";
$text['label-contact_organization']['el-gr'] = "Οργανισμός";
$text['label-contact_organization']['es-cl'] = "Organización";
$text['label-contact_organization']['es-mx'] = "Organización"; //copied from es-cl
$text['label-contact_organization']['fr-ca'] = "Organisation"; //copied from fr-fr
$text['label-contact_organization']['fr-fr'] = "Organisation";
$text['label-contact_organization']['he-il'] = "ארגון";
$text['label-contact_organization']['it-it'] = "Organizzazione";
$text['label-contact_organization']['nl-nl'] = "Organisatie";
$text['label-contact_organization']['pl-pl'] = "Organizacja";
$text['label-contact_organization']['pt-br'] = "Organização"; //copied from pt-pt
$text['label-contact_organization']['pt-pt'] = "Organização";
$text['label-contact_organization']['ro-ro'] = "";
$text['label-contact_organization']['ru-ru'] = "Организация";
$text['label-contact_organization']['sv-se'] = "Organisation";
$text['label-contact_organization']['uk-ua'] = "Організація";

$text['label-contact_name_given']['en-us'] = "First Name";
$text['label-contact_name_given']['en-gb'] = "First Name";
$text['label-contact_name_given']['ar-eg'] = "";
$text['label-contact_name_given']['de-at'] = "Vorname"; //copied from de-de
$text['label-contact_name_given']['de-ch'] = "Vorname"; //copied from de-de
$text['label-contact_name_given']['de-de'] = "Vorname";
$text['label-contact_name_given']['el-gr'] = "Όνομα";
$text['label-contact_name_given']['es-cl'] = "Primer Nombre";
$text['label-contact_name_given']['es-mx'] = "Primer Nombre"; //copied from es-cl
$text['label-contact_name_given']['fr-ca'] = "Prénom"; //copied from fr-fr
$text['label-contact_name_given']['fr-fr'] = "Prénom";
$text['label-contact_name_given']['he-il'] = "שם";
$text['label-contact_name_given']['it-it'] = "Nome";
$text['label-contact_name_given']['nl-nl'] = "Voornaam";
$text['label-contact_name_given']['pl-pl'] = "Imię";
$text['label-contact_name_given']['pt-br'] = "Primeiro nome";
$text['label-contact_name_given']['pt-pt'] = "Primeiro Nome";
$text['label-contact_name_given']['ro-ro'] = "";
$text['label-contact_name_given']['ru-ru'] = "Имя";
$text['label-contact_name_given']['sv-se'] = "Förnamn";
$text['label-contact_name_given']['uk-ua'] = "Ім’я";

$text['label-contact_name_family']['en-us'] = "Last Name";
$text['label-contact_name_family']['en-gb'] = "Last Name";
$text['label-contact_name_family']['ar-eg'] = "";
$text['label-contact_name_family']['de-at'] = "Nachname"; //copied from de-de
$text['label-contact_name_family']['de-ch'] = "Nachname"; //copied from de-de
$text['label-contact_name_family']['de-de'] = "Nachname";
$text['label-contact_name_family']['el-gr'] = "Επώνυμο";
$text['label-contact_name_family']['es-cl'] = "Segundo Nombre";
$text['label-contact_name_family']['es-mx'] = "Segundo Nombre"; //copied from es-cl
$text['label-contact_name_family']['fr-ca'] = "Nom"; //copied from fr-fr
$text['label-contact_name_family']['fr-fr'] = "Nom";
$text['label-contact_name_family']['he-il'] = "שם משפחה";
$text['label-contact_name_family']['it-it'] = "Cognome";
$text['label-contact_name_family']['nl-nl'] = "Achternaam";
$text['label-contact_name_family']['pl-pl'] = "Nazwisko";
$text['label-contact_name_family']['pt-br'] = "Uítimo nome";
$text['label-contact_name_family']['pt-pt'] = "Último nome";
$text['label-contact_name_family']['ro-ro'] = "";
$text['label-contact_name_family']['ru-ru'] = "Фамилия";
$text['label-contact_name_family']['sv-se'] = "Efternamn";
$text['label-contact_name_family']['uk-ua'] = "Прізвище";

$text['label-contact_nickname']['en-us'] = "Nickname";
$text['label-contact_nickname']['en-gb'] = "Nickname";
$text['label-contact_nickname']['ar-eg'] = "";
$text['label-contact_nickname']['de-at'] = "Spitzname"; //copied from de-de
$text['label-contact_nickname']['de-ch'] = "Spitzname"; //copied from de-de
$text['label-contact_nickname']['de-de'] = "Spitzname";
$text['label-contact_nickname']['el-gr'] = "Υποκοριστικό";
$text['label-contact_nickname']['es-cl'] = "Apodo";
$text['label-contact_nickname']['es-mx'] = "Apodo"; //copied from es-cl
$text['label-contact_nickname']['fr-ca'] = "Surnom"; //copied from fr-fr
$text['label-contact_nickname']['fr-fr'] = "Surnom";
$text['label-contact_nickname']['he-il'] = "כינוי";
$text['label-contact_nickname']['it-it'] = "Soprannome";
$text['label-contact_nickname']['nl-nl'] = "Bijnaam";
$text['label-contact_nickname']['pl-pl'] = "Nazwa";
$text['label-contact_nickname']['pt-br'] = "Apelido";
$text['label-contact_nickname']['pt-pt'] = "Nickname";
$text['label-contact_nickname']['ro-ro'] = "";
$text['label-contact_nickname']['ru-ru'] = "Псевдоним пользователя";
$text['label-contact_nickname']['sv-se'] = "Smeknamn";
$text['label-contact_nickname']['uk-ua'] = "Прізвисько";

$text['label-contact_type']['en-us'] = "Type";
$text['label-contact_type']['en-gb'] = "Type";
$text['label-contact_type']['ar-eg'] = "";
$text['label-contact_type']['de-at'] = "Art"; //copied from de-de
$text['label-contact_type']['de-ch'] = "Art"; //copied from de-de
$text['label-contact_type']['de-de'] = "Art";
$text['label-contact_type']['el-gr'] = "Τύπος";
$text['label-contact_type']['es-cl'] = "Tipo";
$text['label-contact_type']['es-mx'] = "Tipo"; //copied from es-cl
$text['label-contact_type']['fr-ca'] = "Type"; //copied from fr-fr
$text['label-contact_type']['fr-fr'] = "Type";
$text['label-contact_type']['he-il'] = "סוג";
$text['label-contact_type']['it-it'] = "Tipo";
$text['label-contact_type']['nl-nl'] = "Typp";
$text['label-contact_type']['pl-pl'] = "Type";
$text['label-contact_type']['pt-br'] = "Tipo"; //copied from pt-pt
$text['label-contact_type']['pt-pt'] = "Tipo";
$text['label-contact_type']['ro-ro'] = "";
$text['label-contact_type']['ru-ru'] = "Тип";
$text['label-contact_type']['sv-se'] = "Typ";
$text['label-contact_type']['uk-ua'] = "Тип";

$text['option-contact_type_all']['en-us'] = "All";
$text['option-contact_type_all']['en-gb'] = "All";
$text['option-contact_type_all']['ar-eg'] = "All";
$text['option-contact_type_all']['de-at'] = "All";
$text['option-contact_type_all']['de-ch'] = "All";
$text['option-contact_type_all']['de-de'] = "All";
$text['option-contact_type_all']['el-gr'] = "All";
$text['option-contact_type_all']['es-cl'] = "All";
$text['option-contact_type_all']['es-mx'] = "All";
$text['option-contact_type_all']['fr-ca'] = "All";
$text['option-contact_type_all']['fr-fr'] = "All";
$text['option-contact_type_all']['he-il'] = "All";
$text['option-contact_type_all']['it-it'] = "All";
$text['option-contact_type_all']['nl-nl'] = "All";
$text['option-contact_type_all']['pl-pl'] = "All";
$text['option-contact_type_all']['pt-br'] = "Todos";
$text['option-contact_type_all']['pt-pt'] = "Todos";
$text['option-contact_type_all']['ro-ro'] = "All";
$text['option-contact_type_all']['ru-ru'] = "All";
$text['option-contact_type_all']['sv-se'] = "All";
$text['option-contact_type_all']['uk-ua'] = "All";

$text['option-contact_type_volunteer']['en-us'] = "Volunteer";
$text['option-contact_type_volunteer']['en-gb'] = "Volunteer";
$text['option-contact_type_volunteer']['ar-eg'] = "";
$text['option-contact_type_volunteer']['de-at'] = "Freiwilliger Helfer"; //copied from de-de
$text['option-contact_type_volunteer']['de-ch'] = "Freiwilliger Helfer"; //copied from de-de
$text['option-contact_type_volunteer']['de-de'] = "Freiwilliger Helfer";
$text['option-contact_type_volunteer']['el-gr'] = "Εθελοντής";
$text['option-contact_type_volunteer']['es-cl'] = "Voluntario";
$text['option-contact_type_volunteer']['es-mx'] = "Voluntario"; //copied from es-cl
$text['option-contact_type_volunteer']['fr-ca'] = "Bénévole"; //copied from fr-fr
$text['option-contact_type_volunteer']['fr-fr'] = "Bénévole";
$text['option-contact_type_volunteer']['he-il'] = "";
$text['option-contact_type_volunteer']['it-it'] = "Volontario";
$text['option-contact_type_volunteer']['nl-nl'] = "Vrijwilliger";
$text['option-contact_type_volunteer']['pl-pl'] = "Wolontariusz";
$text['option-contact_type_volunteer']['pt-br'] = "Voluntário"; //copied from pt-pt
$text['option-contact_type_volunteer']['pt-pt'] = "Voluntário";
$text['option-contact_type_volunteer']['ro-ro'] = "";
$text['option-contact_type_volunteer']['ru-ru'] = "Волонтер";
$text['option-contact_type_volunteer']['sv-se'] = "Frivillig";
$text['option-contact_type_volunteer']['uk-ua'] = "Волонтер";

$text['option-contact_type_user']['en-us'] = "User";
$text['option-contact_type_user']['en-gb'] = "User";
$text['option-contact_type_user']['ar-eg'] = "";
$text['option-contact_type_user']['de-at'] = "Benutzer"; //copied from de-de
$text['option-contact_type_user']['de-ch'] = "Benutzer"; //copied from de-de
$text['option-contact_type_user']['de-de'] = "Benutzer";
$text['option-contact_type_user']['el-gr'] = "Χρήστης";
$text['option-contact_type_user']['es-cl'] = "Usuario";
$text['option-contact_type_user']['es-mx'] = "Usuario"; //copied from es-cl
$text['option-contact_type_user']['fr-ca'] = "Utilisateur"; //copied from fr-fr
$text['option-contact_type_user']['fr-fr'] = "Utilisateur";
$text['option-contact_type_user']['he-il'] = "משתמש";
$text['option-contact_type_user']['it-it'] = "Utente";
$text['option-contact_type_user']['nl-nl'] = "Gebruiker";
$text['option-contact_type_user']['pl-pl'] = "Użytkownik";
$text['option-contact_type_user']['pt-br'] = "Usuário"; //copied from pt-pt
$text['option-contact_type_user']['pt-pt'] = "Usuário";
$text['option-contact_type_user']['ro-ro'] = "";
$text['option-contact_type_user']['ru-ru'] = "Пользователь";
$text['option-contact_type_user']['sv-se'] = "Användare";
$text['option-contact_type_user']['uk-ua'] = "Користувач";

$text['option-contact_type_supplier']['en-us'] = "Supplier";
$text['option-contact_type_supplier']['en-gb'] = "Supplier";
$text['option-contact_type_supplier']['ar-eg'] = "";
$text['option-contact_type_supplier']['de-at'] = "Lieferant"; //copied from de-de
$text['option-contact_type_supplier']['de-ch'] = "Lieferant"; //copied from de-de
$text['option-contact_type_supplier']['de-de'] = "Lieferant";
$text['option-contact_type_supplier']['el-gr'] = "Προμηθευτής";
$text['option-contact_type_supplier']['es-cl'] = "Proveedor";
$text['option-contact_type_supplier']['es-mx'] = "Proveedor"; //copied from es-cl
$text['option-contact_type_supplier']['fr-ca'] = "Fournisseur"; //copied from fr-fr
$text['option-contact_type_supplier']['fr-fr'] = "Fournisseur";
$text['option-contact_type_supplier']['he-il'] = "ספק";
$text['option-contact_type_supplier']['it-it'] = "Fornitore";
$text['option-contact_type_supplier']['nl-nl'] = "Leverancier";
$text['option-contact_type_supplier']['pl-pl'] = "Dostawca";
$text['option-contact_type_supplier']['pt-br'] = "Fornecedor"; //copied from pt-pt
$text['option-contact_type_supplier']['pt-pt'] = "Fornecedor";
$text['option-contact_type_supplier']['ro-ro'] = "";
$text['option-contact_type_supplier']['ru-ru'] = "Поставщик";
$text['option-contact_type_supplier']['sv-se'] = "Leverantör";
$text['option-contact_type_supplier']['uk-ua'] = "Постачальник";

$text['option-contact_type_subscriber']['en-us'] = "Subscriber";
$text['option-contact_type_subscriber']['en-gb'] = "Subscriber";
$text['option-contact_type_subscriber']['ar-eg'] = "";
$text['option-contact_type_subscriber']['de-at'] = "Teilnehmer"; //copied from de-de
$text['option-contact_type_subscriber']['de-ch'] = "Teilnehmer"; //copied from de-de
$text['option-contact_type_subscriber']['de-de'] = "Teilnehmer";
$text['option-contact_type_subscriber']['el-gr'] = "Συνδρομητής";
$text['option-contact_type_subscriber']['es-cl'] = "Suscriptor";
$text['option-contact_type_subscriber']['es-mx'] = "Suscriptor"; //copied from es-cl
$text['option-contact_type_subscriber']['fr-ca'] = "Abonné"; //copied from fr-fr
$text['option-contact_type_subscriber']['fr-fr'] = "Abonné";
$text['option-contact_type_subscriber']['he-il'] = "מנוי";
$text['option-contact_type_subscriber']['it-it'] = "Abbonato";
$text['option-contact_type_subscriber']['nl-nl'] = "Abonnee";
$text['option-contact_type_subscriber']['pl-pl'] = "Abonent";
$text['option-contact_type_subscriber']['pt-br'] = "Assinante"; //copied from pt-pt
$text['option-contact_type_subscriber']['pt-pt'] = "Assinante";
$text['option-contact_type_subscriber']['ro-ro'] = "";
$text['option-contact_type_subscriber']['ru-ru'] = "Подписчик";
$text['option-contact_type_subscriber']['sv-se'] = "Abonnent";
$text['option-contact_type_subscriber']['uk-ua'] = "";

$text['option-contact_type_provider']['en-us'] = "Provider";
$text['option-contact_type_provider']['en-gb'] = "Provider";
$text['option-contact_type_provider']['ar-eg'] = "";
$text['option-contact_type_provider']['de-at'] = "Anbieter"; //copied from de-de
$text['option-contact_type_provider']['de-ch'] = "Anbieter"; //copied from de-de
$text['option-contact_type_provider']['de-de'] = "Anbieter";
$text['option-contact_type_provider']['el-gr'] = "Πάροχος";
$text['option-contact_type_provider']['es-cl'] = "Proveedor";
$text['option-contact_type_provider']['es-mx'] = "Proveedor"; //copied from es-cl
$text['option-contact_type_provider']['fr-ca'] = "Fournisseur"; //copied from fr-fr
$text['option-contact_type_provider']['fr-fr'] = "Fournisseur";
$text['option-contact_type_provider']['he-il'] = "ספק שירות";
$text['option-contact_type_provider']['it-it'] = "Servizi";
$text['option-contact_type_provider']['nl-nl'] = "Beschikbaarsteller";
$text['option-contact_type_provider']['pl-pl'] = "Dostawca";
$text['option-contact_type_provider']['pt-br'] = "Provedor"; //copied from pt-pt
$text['option-contact_type_provider']['pt-pt'] = "Provedor";
$text['option-contact_type_provider']['ro-ro'] = "";
$text['option-contact_type_provider']['ru-ru'] = "Провайдер";
$text['option-contact_type_provider']['sv-se'] = "Leverantör";
$text['option-contact_type_provider']['uk-ua'] = "";

$text['option-contact_type_member']['en-us'] = "Member";
$text['option-contact_type_member']['en-gb'] = "Member";
$text['option-contact_type_member']['ar-eg'] = "";
$text['option-contact_type_member']['de-at'] = "Teilnehmer"; //copied from de-de
$text['option-contact_type_member']['de-ch'] = "Teilnehmer"; //copied from de-de
$text['option-contact_type_member']['de-de'] = "Teilnehmer";
$text['option-contact_type_member']['el-gr'] = "Μέλος";
$text['option-contact_type_member']['es-cl'] = "Miembro";
$text['option-contact_type_member']['es-mx'] = "Miembro"; //copied from es-cl
$text['option-contact_type_member']['fr-ca'] = "Membre"; //copied from fr-fr
$text['option-contact_type_member']['fr-fr'] = "Membre";
$text['option-contact_type_member']['he-il'] = "";
$text['option-contact_type_member']['it-it'] = "Membro";
$text['option-contact_type_member']['nl-nl'] = "Lid";
$text['option-contact_type_member']['pl-pl'] = "Członek";
$text['option-contact_type_member']['pt-br'] = "Membro"; //copied from pt-pt
$text['option-contact_type_member']['pt-pt'] = "Membro";
$text['option-contact_type_member']['ro-ro'] = "";
$text['option-contact_type_member']['ru-ru'] = "Участник";
$text['option-contact_type_member']['sv-se'] = "Medlem";
$text['option-contact_type_member']['uk-ua'] = "Учасник";

$text['option-contact_type_lead']['en-us'] = "Lead";
$text['option-contact_type_lead']['en-gb'] = "Lead";
$text['option-contact_type_lead']['ar-eg'] = "";
$text['option-contact_type_lead']['de-at'] = "Vorgesetzter"; //copied from de-de
$text['option-contact_type_lead']['de-ch'] = "Vorgesetzter"; //copied from de-de
$text['option-contact_type_lead']['de-de'] = "Vorgesetzter";
$text['option-contact_type_lead']['el-gr'] = "Επόπτης";
$text['option-contact_type_lead']['es-cl'] = "Supervisor";
$text['option-contact_type_lead']['es-mx'] = "Supervisor"; //copied from es-cl
$text['option-contact_type_lead']['fr-ca'] = "Superviseur"; //copied from fr-fr
$text['option-contact_type_lead']['fr-fr'] = "Superviseur";
$text['option-contact_type_lead']['he-il'] = "הזדמנות";
$text['option-contact_type_lead']['it-it'] = "Contatto Interno";
$text['option-contact_type_lead']['nl-nl'] = "Hoofd";
$text['option-contact_type_lead']['pl-pl'] = "Szef";
$text['option-contact_type_lead']['pt-br'] = "Supervisor"; //copied from pt-pt
$text['option-contact_type_lead']['pt-pt'] = "Supervisor";
$text['option-contact_type_lead']['ro-ro'] = "";
$text['option-contact_type_lead']['ru-ru'] = "Руководитель";
$text['option-contact_type_lead']['sv-se'] = "'Lead'";
$text['option-contact_type_lead']['uk-ua'] = "";

$text['option-contact_type_friend']['en-us'] = "Friend";
$text['option-contact_type_friend']['en-gb'] = "Friend";
$text['option-contact_type_friend']['ar-eg'] = "";
$text['option-contact_type_friend']['de-at'] = "Freund"; //copied from de-de
$text['option-contact_type_friend']['de-ch'] = "Freund"; //copied from de-de
$text['option-contact_type_friend']['de-de'] = "Freund";
$text['option-contact_type_friend']['el-gr'] = "Φίλος";
$text['option-contact_type_friend']['es-cl'] = "Amigo";
$text['option-contact_type_friend']['es-mx'] = "Amigo"; //copied from es-cl
$text['option-contact_type_friend']['fr-ca'] = "Ami"; //copied from fr-fr
$text['option-contact_type_friend']['fr-fr'] = "Ami";
$text['option-contact_type_friend']['he-il'] = "חבר";
$text['option-contact_type_friend']['it-it'] = "Amico";
$text['option-contact_type_friend']['nl-nl'] = "Vriend";
$text['option-contact_type_friend']['pl-pl'] = "Kolega";
$text['option-contact_type_friend']['pt-br'] = "Amigo"; //copied from pt-pt
$text['option-contact_type_friend']['pt-pt'] = "Amigo";
$text['option-contact_type_friend']['ro-ro'] = "";
$text['option-contact_type_friend']['ru-ru'] = "Друг";
$text['option-contact_type_friend']['sv-se'] = "Vän";
$text['option-contact_type_friend']['uk-ua'] = "";

$text['option-contact_type_family']['en-us'] = "Family";
$text['option-contact_type_family']['en-gb'] = "Family";
$text['option-contact_type_family']['ar-eg'] = "";
$text['option-contact_type_family']['de-at'] = "Familie"; //copied from de-de
$text['option-contact_type_family']['de-ch'] = "Familie"; //copied from de-de
$text['option-contact_type_family']['de-de'] = "Familie";
$text['option-contact_type_family']['el-gr'] = "Οικογένεια";
$text['option-contact_type_family']['es-cl'] = "Familia";
$text['option-contact_type_family']['es-mx'] = "Familia"; //copied from es-cl
$text['option-contact_type_family']['fr-ca'] = "Famille"; //copied from fr-fr
$text['option-contact_type_family']['fr-fr'] = "Famille";
$text['option-contact_type_family']['he-il'] = "משפחה";
$text['option-contact_type_family']['it-it'] = "Famiglia";
$text['option-contact_type_family']['nl-nl'] = "Familie";
$text['option-contact_type_family']['pl-pl'] = "Rodzina";
$text['option-contact_type_family']['pt-br'] = "Familia";
$text['option-contact_type_family']['pt-pt'] = "Família";
$text['option-contact_type_family']['ro-ro'] = "";
$text['option-contact_type_family']['ru-ru'] = "Семейный";
$text['option-contact_type_family']['sv-se'] = "Familj";
$text['option-contact_type_family']['uk-ua'] = "";

$text['option-contact_type_customer']['en-us'] = "Customer";
$text['option-contact_type_customer']['en-gb'] = "Customer";
$text['option-contact_type_customer']['ar-eg'] = "";
$text['option-contact_type_customer']['de-at'] = "Kunde"; //copied from de-de
$text['option-contact_type_customer']['de-ch'] = "Kunde"; //copied from de-de
$text['option-contact_type_customer']['de-de'] = "Kunde";
$text['option-contact_type_customer']['el-gr'] = "Πελάτης";
$text['option-contact_type_customer']['es-cl'] = "Cliente";
$text['option-contact_type_customer']['es-mx'] = "Cliente"; //copied from es-cl
$text['option-contact_type_customer']['fr-ca'] = "Client"; //copied from fr-fr
$text['option-contact_type_customer']['fr-fr'] = "Client";
$text['option-contact_type_customer']['he-il'] = "לקוח";
$text['option-contact_type_customer']['it-it'] = "Cliente";
$text['option-contact_type_customer']['nl-nl'] = "Klant";
$text['option-contact_type_customer']['pl-pl'] = "Klient";
$text['option-contact_type_customer']['pt-br'] = "Cliente ";
$text['option-contact_type_customer']['pt-pt'] = "Cliente";
$text['option-contact_type_customer']['ro-ro'] = "";
$text['option-contact_type_customer']['ru-ru'] = "Клиент";
$text['option-contact_type_customer']['sv-se'] = "Kund";
$text['option-contact_type_customer']['uk-ua'] = "";

$text['option-contact_type_contractor']['en-us'] = "Contractor";
$text['option-contact_type_contractor']['en-gb'] = "Contractor";
$text['option-contact_type_contractor']['ar-eg'] = "";
$text['option-contact_type_contractor']['de-at'] = "Vertragspartner"; //copied from de-de
$text['option-contact_type_contractor']['de-ch'] = "Vertragspartner"; //copied from de-de
$text['option-contact_type_contractor']['de-de'] = "Vertragspartner";
$text['option-contact_type_contractor']['el-gr'] = "Ανάδοχος";
$text['option-contact_type_contractor']['es-cl'] = "Contratista";
$text['option-contact_type_contractor']['es-mx'] = "Contratista"; //copied from es-cl
$text['option-contact_type_contractor']['fr-ca'] = "Entrepreneur"; //copied from fr-fr
$text['option-contact_type_contractor']['fr-fr'] = "Entrepreneur";
$text['option-contact_type_contractor']['he-il'] = "ספק";
$text['option-contact_type_contractor']['it-it'] = "A Contratto";
$text['option-contact_type_contractor']['nl-nl'] = "Uitvoerder";
$text['option-contact_type_contractor']['pl-pl'] = "Kontrahent";
$text['option-contact_type_contractor']['pt-br'] = "Contratante"; //copied from pt-pt
$text['option-contact_type_contractor']['pt-pt'] = "Contratante";
$text['option-contact_type_contractor']['ro-ro'] = "";
$text['option-contact_type_contractor']['ru-ru'] = "Подрядчик";
$text['option-contact_type_contractor']['sv-se'] = "Entreprenör";
$text['option-contact_type_contractor']['uk-ua'] = "";

$text['label-contact_note']['en-us'] = "Note";
$text['label-contact_note']['en-gb'] = "Note";
$text['label-contact_note']['ar-eg'] = "";
$text['label-contact_note']['de-at'] = "Notiz"; //copied from de-de
$text['label-contact_note']['de-ch'] = "Notiz"; //copied from de-de
$text['label-contact_note']['de-de'] = "Notiz";
$text['label-contact_note']['el-gr'] = "Σημείωση";
$text['label-contact_note']['es-cl'] = "Nota";
$text['label-contact_note']['es-mx'] = "Nota"; //copied from es-cl
$text['label-contact_note']['fr-ca'] = "Note"; //copied from fr-fr
$text['label-contact_note']['fr-fr'] = "Note";
$text['label-contact_note']['he-il'] = "הערה";
$text['label-contact_note']['it-it'] = "Nota";
$text['label-contact_note']['nl-nl'] = "Notitie";
$text['label-contact_note']['pl-pl'] = "Notatka";
$text['label-contact_note']['pt-br'] = "Nota"; //copied from pt-pt
$text['label-contact_note']['pt-pt'] = "Nota";
$text['label-contact_note']['ro-ro'] = "";
$text['label-contact_note']['ru-ru'] = "Примечание";
$text['label-contact_note']['sv-se'] = "Notering";
$text['label-contact_note']['uk-ua'] = "Нотатка";

$text['label-phone_label']['en-us'] = "Phone Label";
$text['label-phone_label']['en-gb'] = "Phone Label";
$text['label-phone_label']['ar-eg'] = "";
$text['label-phone_label']['de-at'] = "Kennzeichnung"; //copied from de-de
$text['label-phone_label']['de-ch'] = "Kennzeichnung"; //copied from de-de
$text['label-phone_label']['de-de'] = "Kennzeichnung";
$text['label-phone_label']['el-gr'] = "Ετικέτα";
$text['label-phone_label']['es-cl'] = "Etiqueta";
$text['label-phone_label']['es-mx'] = "Etiqueta"; //copied from es-cl
$text['label-phone_label']['fr-ca'] = "Etiquette"; //copied from fr-fr
$text['label-phone_label']['fr-fr'] = "Etiquette";
$text['label-phone_label']['he-il'] = "";
$text['label-phone_label']['it-it'] = "Etichetta";
$text['label-phone_label']['nl-nl'] = "Etiket";
$text['label-phone_label']['pl-pl'] = "Etykieta";
$text['label-phone_label']['pt-br'] = "Tipo de Número";
$text['label-phone_label']['pt-pt'] = "Etiqueta";
$text['label-phone_label']['ro-ro'] = "";
$text['label-phone_label']['ru-ru'] = "Метка";
$text['label-phone_label']['sv-se'] = "Etikett";
$text['label-phone_label']['uk-ua'] = "Назва";

$text['option-work']['en-us'] = "Work";
$text['option-work']['en-gb'] = "Work";
$text['option-work']['ar-eg'] = "";
$text['option-work']['de-at'] = "Arbeit"; //copied from de-de
$text['option-work']['de-ch'] = "Arbeit"; //copied from de-de
$text['option-work']['de-de'] = "Arbeit";
$text['option-work']['el-gr'] = "Εργασία";
$text['option-work']['es-cl'] = "Lugar de Trabajo";
$text['option-work']['es-mx'] = "Lugar de Trabajo"; //copied from es-cl
$text['option-work']['fr-ca'] = "Travail";
$text['option-work']['fr-fr'] = "En Milieu de Travail";
$text['option-work']['he-il'] = "עבודה";
$text['option-work']['it-it'] = "Lavoro";
$text['option-work']['nl-nl'] = "Werk";
$text['option-work']['pl-pl'] = "Praca";
$text['option-work']['pt-br'] = "Local de trabalho";
$text['option-work']['pt-pt'] = "Local de Trabalho";
$text['option-work']['ro-ro'] = "";
$text['option-work']['ru-ru'] = "Работа";
$text['option-work']['sv-se'] = "Arbete";
$text['option-work']['uk-ua'] = "";

$text['option-home']['en-us'] = "Home";
$text['option-home']['en-gb'] = "Home";
$text['option-home']['ar-eg'] = "";
$text['option-home']['de-at'] = "Privat"; //copied from de-de
$text['option-home']['de-ch'] = "Privat"; //copied from de-de
$text['option-home']['de-de'] = "Privat";
$text['option-home']['el-gr'] = "Αρχική";
$text['option-home']['es-cl'] = "Casa";
$text['option-home']['es-mx'] = "Casa"; //copied from es-cl
$text['option-home']['fr-ca'] = "Domicile";
$text['option-home']['fr-fr'] = "Maison";
$text['option-home']['he-il'] = "בית";
$text['option-home']['it-it'] = "Casa";
$text['option-home']['nl-nl'] = "Huis";
$text['option-home']['pl-pl'] = "Dom";
$text['option-home']['pt-br'] = "Casa"; //copied from pt-pt
$text['option-home']['pt-pt'] = "Casa";
$text['option-home']['ro-ro'] = "";
$text['option-home']['ru-ru'] = "Главная";
$text['option-home']['sv-se'] = "Hem";
$text['option-home']['uk-ua'] = "Домашній";

$text['option-mobile']['en-us'] = "Mobile";
$text['option-mobile']['en-gb'] = "Mobile";
$text['option-mobile']['ar-eg'] = "";
$text['option-mobile']['de-at'] = "Mobil"; //copied from de-de
$text['option-mobile']['de-ch'] = "Mobil"; //copied from de-de
$text['option-mobile']['de-de'] = "Mobil";
$text['option-mobile']['el-gr'] = "Κινητό";
$text['option-mobile']['es-cl'] = "Celular";
$text['option-mobile']['es-mx'] = "Celular"; //copied from es-cl
$text['option-mobile']['fr-ca'] = "Cellulaire"; //copied from fr-fr
$text['option-mobile']['fr-fr'] = "Cellulaire";
$text['option-mobile']['he-il'] = "נייד";
$text['option-mobile']['it-it'] = "Mobile";
$text['option-mobile']['nl-nl'] = "Mobiel";
$text['option-mobile']['pl-pl'] = "Tel komórkowy";
$text['option-mobile']['pt-br'] = "Celular"; //copied from pt-pt
$text['option-mobile']['pt-pt'] = "Celular";
$text['option-mobile']['ro-ro'] = "";
$text['option-mobile']['ru-ru'] = "Мобильний";
$text['option-mobile']['sv-se'] = "Mobil";
$text['option-mobile']['uk-ua'] = "Мобільний";

$text['option-main']['en-us'] = "Main";
$text['option-main']['en-gb'] = "Main";
$text['option-main']['ar-eg'] = "";
$text['option-main']['de-at'] = "Vorrangig"; //copied from de-de
$text['option-main']['de-ch'] = "Vorrangig"; //copied from de-de
$text['option-main']['de-de'] = "Vorrangig";
$text['option-main']['el-gr'] = "Κύριο";
$text['option-main']['es-cl'] = "Principal";
$text['option-main']['es-mx'] = "Principal"; //copied from es-cl
$text['option-main']['fr-ca'] = "Principal"; //copied from fr-fr
$text['option-main']['fr-fr'] = "Principal";
$text['option-main']['he-il'] = "ראשי";
$text['option-main']['it-it'] = "Principale";
$text['option-main']['nl-nl'] = "Hoofd";
$text['option-main']['pl-pl'] = "Główny";
$text['option-main']['pt-br'] = "Principal"; //copied from pt-pt
$text['option-main']['pt-pt'] = "Principal";
$text['option-main']['ro-ro'] = "";
$text['option-main']['ru-ru'] = "Главный";
$text['option-main']['sv-se'] = "Huvud";
$text['option-main']['uk-ua'] = "Основний";

$text['option-billing']['en-us'] = "Billing";
$text['option-billing']['en-gb'] = "Billing";
$text['option-billing']['ar-eg'] = "";
$text['option-billing']['de-at'] = "Verrechnung"; //copied from de-de
$text['option-billing']['de-ch'] = "Verrechnung"; //copied from de-de
$text['option-billing']['de-de'] = "Verrechnung";
$text['option-billing']['el-gr'] = "Χρεώσεις";
$text['option-billing']['es-cl'] = "Facturación";
$text['option-billing']['es-mx'] = "Facturación"; //copied from es-cl
$text['option-billing']['fr-ca'] = "Facturation"; //copied from fr-fr
$text['option-billing']['fr-fr'] = "Facturation";
$text['option-billing']['he-il'] = "";
$text['option-billing']['it-it'] = "Fatturazione";
$text['option-billing']['nl-nl'] = "Verrekening";
$text['option-billing']['pl-pl'] = "Rozliczenia";
$text['option-billing']['pt-br'] = "Faturamento"; //copied from pt-pt
$text['option-billing']['pt-pt'] = "Faturamento";
$text['option-billing']['ro-ro'] = "";
$text['option-billing']['ru-ru'] = "Биллинг";
$text['option-billing']['sv-se'] = "Fakturering";
$text['option-billing']['uk-ua'] = "Білінг";

$text['option-fax']['en-us'] = "Fax";
$text['option-fax']['en-gb'] = "Fax";
$text['option-fax']['ar-eg'] = "";
$text['option-fax']['de-at'] = "Fax"; //copied from de-de
$text['option-fax']['de-ch'] = "Fax"; //copied from de-de
$text['option-fax']['de-de'] = "Fax";
$text['option-fax']['el-gr'] = "Τηλεομοιότυπο";
$text['option-fax']['es-cl'] = "Facsímil";
$text['option-fax']['es-mx'] = "Facsímil"; //copied from es-cl
$text['option-fax']['fr-ca'] = "Télécopie"; //copied from fr-fr
$text['option-fax']['fr-fr'] = "Télécopie";
$text['option-fax']['he-il'] = "פקס";
$text['option-fax']['it-it'] = "Fax";
$text['option-fax']['nl-nl'] = "Fax";
$text['option-fax']['pl-pl'] = "Faks";
$text['option-fax']['pt-br'] = "FAX";
$text['option-fax']['pt-pt'] = "Fax";
$text['option-fax']['ro-ro'] = "";
$text['option-fax']['ru-ru'] = "Факс";
$text['option-fax']['sv-se'] = "Fax";
$text['option-fax']['uk-ua'] = "Факс";

$text['option-voicemail']['en-us'] = "Voicemail";
$text['option-voicemail']['en-gb'] = "Voicemail";
$text['option-voicemail']['ar-eg'] = "";
$text['option-voicemail']['de-at'] = "Mailbox"; //copied from de-de
$text['option-voicemail']['de-ch'] = "Mailbox"; //copied from de-de
$text['option-voicemail']['de-de'] = "Mailbox";
$text['option-voicemail']['el-gr'] = "Φωνοκιβώτιο";
$text['option-voicemail']['es-cl'] = "Correo de Voz";
$text['option-voicemail']['es-mx'] = "Correo de Voz"; //copied from es-cl
$text['option-voicemail']['fr-ca'] = "Messagerie Vocale"; //copied from fr-fr
$text['option-voicemail']['fr-fr'] = "Messagerie Vocale";
$text['option-voicemail']['he-il'] = "תא קולי";
$text['option-voicemail']['it-it'] = "Casella Vocale";
$text['option-voicemail']['nl-nl'] = "Antwoord apparaat";
$text['option-voicemail']['pl-pl'] = "Poczta głosowa";
$text['option-voicemail']['pt-br'] = "Correio de Voz";
$text['option-voicemail']['pt-pt'] = "Voicemail";
$text['option-voicemail']['ro-ro'] = "";
$text['option-voicemail']['ru-ru'] = "Голосовая почта";
$text['option-voicemail']['sv-se'] = "Röstbrevlåda";
$text['option-voicemail']['uk-ua'] = "Голосова пошта";

$text['option-text']['en-us'] = "Text";
$text['option-text']['en-gb'] = "Text";
$text['option-text']['ar-eg'] = "";
$text['option-text']['de-at'] = "Text"; //copied from de-de
$text['option-text']['de-ch'] = "Text"; //copied from de-de
$text['option-text']['de-de'] = "Text";
$text['option-text']['el-gr'] = "Κείμενο";
$text['option-text']['es-cl'] = "Texto";
$text['option-text']['es-mx'] = "Texto"; //copied from es-cl
$text['option-text']['fr-ca'] = "Texte"; //copied from fr-fr
$text['option-text']['fr-fr'] = "Texte";
$text['option-text']['he-il'] = "טקסט";
$text['option-text']['it-it'] = "Testo";
$text['option-text']['nl-nl'] = "Tekst";
$text['option-text']['pl-pl'] = "Tekst";
$text['option-text']['pt-br'] = "Texto"; //copied from pt-pt
$text['option-text']['pt-pt'] = "Texto";
$text['option-text']['ro-ro'] = "";
$text['option-text']['ru-ru'] = "Текст";
$text['option-text']['sv-se'] = "Text";
$text['option-text']['uk-ua'] = "Текст";

$text['option-other']['en-us'] = "Other";
$text['option-other']['en-gb'] = "Other";
$text['option-other']['ar-eg'] = "";
$text['option-other']['de-at'] = "Andere"; //copied from de-de
$text['option-other']['de-ch'] = "Andere"; //copied from de-de
$text['option-other']['de-de'] = "Andere";
$text['option-other']['el-gr'] = "Άλλα";
$text['option-other']['es-cl'] = "Otro";
$text['option-other']['es-mx'] = "Otro"; //copied from es-cl
$text['option-other']['fr-ca'] = "Autre"; //copied from fr-fr
$text['option-other']['fr-fr'] = "Autre";
$text['option-other']['he-il'] = "אחר";
$text['option-other']['it-it'] = "Altro";
$text['option-other']['nl-nl'] = "Anders";
$text['option-other']['pl-pl'] = "Inne";
$text['option-other']['pt-br'] = "Outro"; //copied from pt-pt
$text['option-other']['pt-pt'] = "Outro";
$text['option-other']['ro-ro'] = "";
$text['option-other']['ru-ru'] = "Другие";
$text['option-other']['sv-se'] = "Annat";
$text['option-other']['uk-ua'] = "";

$text['label-phone_number']['en-us'] = "Phone Number";
$text['label-phone_number']['en-gb'] = "Phone Number";
$text['label-phone_number']['ar-eg'] = "";
$text['label-phone_number']['de-at'] = "Nummer"; //copied from de-de
$text['label-phone_number']['de-ch'] = "Nummer"; //copied from de-de
$text['label-phone_number']['de-de'] = "Nummer";
$text['label-phone_number']['el-gr'] = "Αριθμός";
$text['label-phone_number']['es-cl'] = "Número";
$text['label-phone_number']['es-mx'] = "Número"; //copied from es-cl
$text['label-phone_number']['fr-ca'] = "Numéro"; //copied from fr-fr
$text['label-phone_number']['fr-fr'] = "Numéro";
$text['label-phone_number']['he-il'] = "מספר";
$text['label-phone_number']['it-it'] = "Numero";
$text['label-phone_number']['nl-nl'] = "Nummer";
$text['label-phone_number']['pl-pl'] = "Numer";
$text['label-phone_number']['pt-br'] = "Número"; //copied from pt-pt
$text['label-phone_number']['pt-pt'] = "Número";
$text['label-phone_number']['ro-ro'] = "";
$text['label-phone_number']['ru-ru'] = "Номер";
$text['label-phone_number']['sv-se'] = "Nummer";
$text['label-phone_number']['uk-ua'] = "Номер";

$text['label-address_type']['en-us'] = "Address Type";
$text['label-address_type']['en-gb'] = "Address Type";
$text['label-address_type']['ar-eg'] = "";
$text['label-address_type']['de-at'] = "Art"; //copied from de-de
$text['label-address_type']['de-ch'] = "Art"; //copied from de-de
$text['label-address_type']['de-de'] = "Art";
$text['label-address_type']['el-gr'] = "Τύπος";
$text['label-address_type']['es-cl'] = "Tipo";
$text['label-address_type']['es-mx'] = "Tipo"; //copied from es-cl
$text['label-address_type']['fr-ca'] = "Type"; //copied from fr-fr
$text['label-address_type']['fr-fr'] = "Type";
$text['label-address_type']['he-il'] = "סוג";
$text['label-address_type']['it-it'] = "Tipo";
$text['label-address_type']['nl-nl'] = "Type";
$text['label-address_type']['pl-pl'] = "Typ";
$text['label-address_type']['pt-br'] = "Tipo de Endereço"; //copied from pt-pt
$text['label-address_type']['pt-pt'] = "Tipo de Endereço";
$text['label-address_type']['ro-ro'] = "";
$text['label-address_type']['ru-ru'] = "Тип";
$text['label-address_type']['sv-se'] = "Typ";
$text['label-address_type']['uk-ua'] = "Тип";

$text['option-dom']['en-us'] = "Domestic";
$text['option-dom']['en-gb'] = "Domestic";
$text['option-dom']['ar-eg'] = "";
$text['option-dom']['de-at'] = "Lokal"; //copied from de-de
$text['option-dom']['de-ch'] = "Lokal"; //copied from de-de
$text['option-dom']['de-de'] = "Lokal";
$text['option-dom']['el-gr'] = "Τοπικό";
$text['option-dom']['es-cl'] = "Doméstico";
$text['option-dom']['es-mx'] = "Doméstico"; //copied from es-cl
$text['option-dom']['fr-ca'] = "Domestique"; //copied from fr-fr
$text['option-dom']['fr-fr'] = "Domestique";
$text['option-dom']['he-il'] = "";
$text['option-dom']['it-it'] = "Domestico";
$text['option-dom']['nl-nl'] = "Lokaal";
$text['option-dom']['pl-pl'] = "Krajowy";
$text['option-dom']['pt-br'] = "Doméstico"; //copied from pt-pt
$text['option-dom']['pt-pt'] = "Doméstico";
$text['option-dom']['ro-ro'] = "";
$text['option-dom']['ru-ru'] = "Внутренние";
$text['option-dom']['sv-se'] = "Inhemsk";
$text['option-dom']['uk-ua'] = "Домашній";

$text['option-intl']['en-us'] = "International";
$text['option-intl']['en-gb'] = "International";
$text['option-intl']['ar-eg'] = "";
$text['option-intl']['de-at'] = "International"; //copied from de-de
$text['option-intl']['de-ch'] = "International"; //copied from de-de
$text['option-intl']['de-de'] = "International";
$text['option-intl']['el-gr'] = "Διεθνής";
$text['option-intl']['es-cl'] = "Internacional";
$text['option-intl']['es-mx'] = "Internacional"; //copied from es-cl
$text['option-intl']['fr-ca'] = "International"; //copied from fr-fr
$text['option-intl']['fr-fr'] = "International";
$text['option-intl']['he-il'] = "בילאומי";
$text['option-intl']['it-it'] = "Internazionale";
$text['option-intl']['nl-nl'] = "Internationaal";
$text['option-intl']['pl-pl'] = "Międzynarodowy";
$text['option-intl']['pt-br'] = "Internacional"; //copied from pt-pt
$text['option-intl']['pt-pt'] = "Internacional";
$text['option-intl']['ro-ro'] = "";
$text['option-intl']['ru-ru'] = "Международный";
$text['option-intl']['sv-se'] = "Internationell";
$text['option-intl']['uk-ua'] = "Міжнародний";

$text['option-postal']['en-us'] = "Postal";
$text['option-postal']['en-gb'] = "Postal";
$text['option-postal']['ar-eg'] = "";
$text['option-postal']['de-at'] = "Postalisch"; //copied from de-de
$text['option-postal']['de-ch'] = "Postalisch"; //copied from de-de
$text['option-postal']['de-de'] = "Postalisch";
$text['option-postal']['el-gr'] = "Ταχυδρομικός";
$text['option-postal']['es-cl'] = "Postal";
$text['option-postal']['es-mx'] = "Postal"; //copied from es-cl
$text['option-postal']['fr-ca'] = "Postal"; //copied from fr-fr
$text['option-postal']['fr-fr'] = "Postal";
$text['option-postal']['he-il'] = "דואר";
$text['option-postal']['it-it'] = "Postale";
$text['option-postal']['nl-nl'] = "per post";
$text['option-postal']['pl-pl'] = "Adres pocztowy";
$text['option-postal']['pt-br'] = "Postal"; //copied from pt-pt
$text['option-postal']['pt-pt'] = "Postal";
$text['option-postal']['ro-ro'] = "";
$text['option-postal']['ru-ru'] = "Почтовый";
$text['option-postal']['sv-se'] = "Postkod";
$text['option-postal']['uk-ua'] = "";

$text['option-parcel']['en-us'] = "Parcel";
$text['option-parcel']['en-gb'] = "Parcel";
$text['option-parcel']['ar-eg'] = "";
$text['option-parcel']['de-at'] = "Paket"; //copied from de-de
$text['option-parcel']['de-ch'] = "Paket"; //copied from de-de
$text['option-parcel']['de-de'] = "Paket";
$text['option-parcel']['el-gr'] = "Δέμα";
$text['option-parcel']['es-cl'] = "Parcela";
$text['option-parcel']['es-mx'] = "Parcela"; //copied from es-cl
$text['option-parcel']['fr-ca'] = "Parcelle"; //copied from fr-fr
$text['option-parcel']['fr-fr'] = "Parcelle";
$text['option-parcel']['he-il'] = "";
$text['option-parcel']['it-it'] = "Collo";
$text['option-parcel']['nl-nl'] = "Pakket";
$text['option-parcel']['pl-pl'] = "Paczka";
$text['option-parcel']['pt-br'] = "Parcela"; //copied from pt-pt
$text['option-parcel']['pt-pt'] = "Parcela";
$text['option-parcel']['ro-ro'] = "";
$text['option-parcel']['ru-ru'] = "Пакет";
$text['option-parcel']['sv-se'] = "Paket";
$text['option-parcel']['uk-ua'] = "";

$text['option-pref']['en-us'] = "Preferred";
$text['option-pref']['en-gb'] = "Preferred";
$text['option-pref']['ar-eg'] = "";
$text['option-pref']['de-at'] = "Bevorzugt"; //copied from de-de
$text['option-pref']['de-ch'] = "Bevorzugt"; //copied from de-de
$text['option-pref']['de-de'] = "Bevorzugt";
$text['option-pref']['el-gr'] = "Προτιμώμενο";
$text['option-pref']['es-cl'] = "Preferido";
$text['option-pref']['es-mx'] = "Preferido"; //copied from es-cl
$text['option-pref']['fr-ca'] = "Préféré"; //copied from fr-fr
$text['option-pref']['fr-fr'] = "Préféré";
$text['option-pref']['he-il'] = "מועדף";
$text['option-pref']['it-it'] = "Preferito";
$text['option-pref']['nl-nl'] = "Voorkeur";
$text['option-pref']['pl-pl'] = "Preferowany";
$text['option-pref']['pt-br'] = "Perferido";
$text['option-pref']['pt-pt'] = "Preferido";
$text['option-pref']['ro-ro'] = "";
$text['option-pref']['ru-ru'] = "Предпочтительный";
$text['option-pref']['sv-se'] = "Föredragen";
$text['option-pref']['uk-ua'] = "";

$text['label-address_address']['en-us'] = "Address";
$text['label-address_address']['en-gb'] = "Address";
$text['label-address_address']['ar-eg'] = "";
$text['label-address_address']['de-at'] = "Adresse"; //copied from de-de
$text['label-address_address']['de-ch'] = "Adresse"; //copied from de-de
$text['label-address_address']['de-de'] = "Adresse";
$text['label-address_address']['el-gr'] = "Διεύθυνση";
$text['label-address_address']['es-cl'] = "Calle";
$text['label-address_address']['es-mx'] = "Calle"; //copied from es-cl
$text['label-address_address']['fr-ca'] = "Adresse"; //copied from fr-fr
$text['label-address_address']['fr-fr'] = "Adresse";
$text['label-address_address']['he-il'] = "כתובת";
$text['label-address_address']['it-it'] = "Indirizzo";
$text['label-address_address']['nl-nl'] = "Adres";
$text['label-address_address']['pl-pl'] = "Adres";
$text['label-address_address']['pt-br'] = "Endereço";
$text['label-address_address']['pt-pt'] = "Rua";
$text['label-address_address']['ro-ro'] = "";
$text['label-address_address']['ru-ru'] = "Адрес";
$text['label-address_address']['sv-se'] = "Adress";
$text['label-address_address']['uk-ua'] = "Адреси";

$text['label-address_locality']['en-us'] = "City";
$text['label-address_locality']['en-gb'] = "City";
$text['label-address_locality']['ar-eg'] = "";
$text['label-address_locality']['de-at'] = "Stadt"; //copied from de-de
$text['label-address_locality']['de-ch'] = "Stadt"; //copied from de-de
$text['label-address_locality']['de-de'] = "Stadt";
$text['label-address_locality']['el-gr'] = "Πόλη";
$text['label-address_locality']['es-cl'] = "Ciudad";
$text['label-address_locality']['es-mx'] = "Ciudad"; //copied from es-cl
$text['label-address_locality']['fr-ca'] = "Ville"; //copied from fr-fr
$text['label-address_locality']['fr-fr'] = "Ville";
$text['label-address_locality']['he-il'] = "עיר";
$text['label-address_locality']['it-it'] = "Città";
$text['label-address_locality']['nl-nl'] = "Stad";
$text['label-address_locality']['pl-pl'] = "MIasto";
$text['label-address_locality']['pt-br'] = "Cidade"; //copied from pt-pt
$text['label-address_locality']['pt-pt'] = "Cidade";
$text['label-address_locality']['ro-ro'] = "";
$text['label-address_locality']['ru-ru'] = "Город";
$text['label-address_locality']['sv-se'] = "Stad";
$text['label-address_locality']['uk-ua'] = "Місто";

$text['label-address_region']['en-us'] = "Region";
$text['label-address_region']['en-gb'] = "Region";
$text['label-address_region']['ar-eg'] = "";
$text['label-address_region']['de-at'] = "Region"; //copied from de-de
$text['label-address_region']['de-ch'] = "Region"; //copied from de-de
$text['label-address_region']['de-de'] = "Region";
$text['label-address_region']['el-gr'] = "Περιοχή";
$text['label-address_region']['es-cl'] = "Región";
$text['label-address_region']['es-mx'] = "Región"; //copied from es-cl
$text['label-address_region']['fr-ca'] = "Région"; //copied from fr-fr
$text['label-address_region']['fr-fr'] = "Région";
$text['label-address_region']['he-il'] = "";
$text['label-address_region']['it-it'] = "Regione";
$text['label-address_region']['nl-nl'] = "Regio";
$text['label-address_region']['pl-pl'] = "Region";
$text['label-address_region']['pt-br'] = "Bairro ";
$text['label-address_region']['pt-pt'] = "Região";
$text['label-address_region']['ro-ro'] = "";
$text['label-address_region']['ru-ru'] = "Область";
$text['label-address_region']['sv-se'] = "Region";
$text['label-address_region']['uk-ua'] = "Область";

$text['label-address_postal_code']['en-us'] = "Postal Code";
$text['label-address_postal_code']['en-gb'] = "Postal Code";
$text['label-address_postal_code']['ar-eg'] = "";
$text['label-address_postal_code']['de-at'] = "PLZ"; //copied from de-de
$text['label-address_postal_code']['de-ch'] = "PLZ"; //copied from de-de
$text['label-address_postal_code']['de-de'] = "PLZ";
$text['label-address_postal_code']['el-gr'] = "Τ.Κ.";
$text['label-address_postal_code']['es-cl'] = "Código Postal";
$text['label-address_postal_code']['es-mx'] = "Código Postal"; //copied from es-cl
$text['label-address_postal_code']['fr-ca'] = "Code Postal"; //copied from fr-fr
$text['label-address_postal_code']['fr-fr'] = "Code Postal";
$text['label-address_postal_code']['he-il'] = "תא דואר";
$text['label-address_postal_code']['it-it'] = "C.A.P.";
$text['label-address_postal_code']['nl-nl'] = "Postcode";
$text['label-address_postal_code']['pl-pl'] = "Kod pocztowy";
$text['label-address_postal_code']['pt-br'] = "Código Postal"; //copied from pt-pt
$text['label-address_postal_code']['pt-pt'] = "Código Postal";
$text['label-address_postal_code']['ro-ro'] = "";
$text['label-address_postal_code']['ru-ru'] = "Почтовый индекс";
$text['label-address_postal_code']['sv-se'] = "Postkod";
$text['label-address_postal_code']['uk-ua'] = "Поштовий індекс";

$text['label-address_country']['en-us'] = "Country";
$text['label-address_country']['en-gb'] = "Country";
$text['label-address_country']['ar-eg'] = "";
$text['label-address_country']['de-at'] = "Land"; //copied from de-de
$text['label-address_country']['de-ch'] = "Land"; //copied from de-de
$text['label-address_country']['de-de'] = "Land";
$text['label-address_country']['el-gr'] = "Χώρα";
$text['label-address_country']['es-cl'] = "País";
$text['label-address_country']['es-mx'] = "País"; //copied from es-cl
$text['label-address_country']['fr-ca'] = "Pays"; //copied from fr-fr
$text['label-address_country']['fr-fr'] = "Pays";
$text['label-address_country']['he-il'] = "מדינה";
$text['label-address_country']['it-it'] = "Paese";
$text['label-address_country']['nl-nl'] = "Land";
$text['label-address_country']['pl-pl'] = "Kraj";
$text['label-address_country']['pt-br'] = "País"; //copied from pt-pt
$text['label-address_country']['pt-pt'] = "País";
$text['label-address_country']['ro-ro'] = "";
$text['label-address_country']['ru-ru'] = "Страна";
$text['label-address_country']['sv-se'] = "Land";
$text['label-address_country']['uk-ua'] = "Країна";

$text['label-email_address']['en-us'] = "Email";
$text['label-email_address']['en-gb'] = "Email";
$text['label-email_address']['ar-eg'] = "";
$text['label-email_address']['de-at'] = "Email-Adresse"; //copied from de-de
$text['label-email_address']['de-ch'] = "Email-Adresse"; //copied from de-de
$text['label-email_address']['de-de'] = "Email-Adresse";
$text['label-email_address']['el-gr'] = "Ηλεκτρονική διεύθυνση";
$text['label-email_address']['es-cl'] = "Calle";
$text['label-email_address']['es-mx'] = "Calle"; //copied from es-cl
$text['label-email_address']['fr-ca'] = "Courriel"; 
$text['label-email_address']['fr-fr'] = "Courriel";
$text['label-email_address']['he-il'] = "כתובת מייל";
$text['label-email_address']['it-it'] = "Indirizzo";
$text['label-email_address']['nl-nl'] = "E-mail Adres";
$text['label-email_address']['pl-pl'] = "Adres email";
$text['label-email_address']['pt-br'] = "Endereço de E-mail";
$text['label-email_address']['pt-pt'] = "Rua";
$text['label-email_address']['ro-ro'] = "";
$text['label-email_address']['ru-ru'] = "Адреса Электронной Почты";
$text['label-email_address']['sv-se'] = "Adress";
$text['label-email_address']['uk-ua'] = "Адреси E-Mail";

$text['label-contact_relation']['en-us'] = "Associate this contact with you?";
$text['label-contact_relation']['en-gb'] = "Associate this contact with you?";
$text['label-contact_relation']['ar-eg'] = "Associate this contact with you?";
$text['label-contact_relation']['de-at'] = "Associate this contact with you?";
$text['label-contact_relation']['de-ch'] = "Associate this contact with you?";
$text['label-contact_relation']['de-de'] = "Associate this contact with you?";
$text['label-contact_relation']['el-gr'] = "Associate this contact with you?";
$text['label-contact_relation']['es-cl'] = "Associate this contact with you?";
$text['label-contact_relation']['es-mx'] = "Associate this contact with you?";
$text['label-contact_relation']['fr-ca'] = "Associate this contact with you?";
$text['label-contact_relation']['fr-fr'] = "Associate this contact with you?";
$text['label-contact_relation']['he-il'] = "Associate this contact with you?";
$text['label-contact_relation']['it-it'] = "Associate this contact with you?";
$text['label-contact_relation']['nl-nl'] = "Associate this contact with you?";
$text['label-contact_relation']['pl-pl'] = "Associate this contact with you?";
$text['label-contact_relation']['pt-br'] = "Associate this contact with you?";
$text['label-contact_relation']['pt-pt'] = "Associate this contact with you?";
$text['label-contact_relation']['ro-ro'] = "Associate this contact with you?";
$text['label-contact_relation']['ru-ru'] = "Associate this contact with you?";
$text['label-contact_relation']['sv-se'] = "Associate this contact with you?";
$text['label-contact_relation']['uk-ua'] = "Associate this contact with you?";

//PHONE----------------------------------------------------

$text['status-not_registered']['en-us'] = "Not Registered";
$text['status-not_registered']['en-gb'] = "Not Registered";
$text['status-not_registered']['ar-eg'] = "Not Registered";
$text['status-not_registered']['de-at'] = "Not Registered";
$text['status-not_registered']['de-ch'] = "Not Registered";
$text['status-not_registered']['de-de'] = "Not Registered";
$text['status-not_registered']['el-gr'] = "Not Registered";
$text['status-not_registered']['es-cl'] = "Not Registered";
$text['status-not_registered']['es-mx'] = "Not Registered";
$text['status-not_registered']['fr-ca'] = "Not Registered";
$text['status-not_registered']['fr-fr'] = "Not Registered";
$text['status-not_registered']['he-il'] = "Not Registered";
$text['status-not_registered']['it-it'] = "Not Registered";
$text['status-not_registered']['nl-nl'] = "Not Registered";
$text['status-not_registered']['pl-pl'] = "Not Registered";
$text['status-not_registered']['pt-br'] = "Not Registered";
$text['status-not_registered']['pt-pt'] = "Not Registered";
$text['status-not_registered']['ro-ro'] = "Not Registered";
$text['status-not_registered']['ru-ru'] = "Not Registered";
$text['status-not_registered']['sv-se'] = "Not Registered";
$text['status-not_registered']['uk-ua'] = "Not Registered";

$text['status-registered']['en-us'] = "Registered";
$text['status-registered']['en-gb'] = "Registered";
$text['status-registered']['ar-eg'] = "Registered";
$text['status-registered']['de-at'] = "Registered";
$text['status-registered']['de-ch'] = "Registered";
$text['status-registered']['de-de'] = "Registered";
$text['status-registered']['el-gr'] = "Registered";
$text['status-registered']['es-cl'] = "Registered";
$text['status-registered']['es-mx'] = "Registered";
$text['status-registered']['fr-ca'] = "Registered";
$text['status-registered']['fr-fr'] = "Registered";
$text['status-registered']['he-il'] = "Registered";
$text['status-registered']['it-it'] = "Registered";
$text['status-registered']['nl-nl'] = "Registered";
$text['status-registered']['pl-pl'] = "Registered";
$text['status-registered']['pt-br'] = "Registered";
$text['status-registered']['pt-pt'] = "Registered";
$text['status-registered']['ro-ro'] = "Registered";
$text['status-registered']['ru-ru'] = "Registered";
$text['status-registered']['sv-se'] = "Registered";
$text['status-registered']['uk-ua'] = "Registered";

$text['status-ringing']['en-us'] = "Ringing";
$text['status-ringing']['en-gb'] = "Ringing";
$text['status-ringing']['ar-eg'] = "Ringing";
$text['status-ringing']['de-at'] = "Ringing";
$text['status-ringing']['de-ch'] = "Ringing";
$text['status-ringing']['de-de'] = "Ringing";
$text['status-ringing']['el-gr'] = "Ringing";
$text['status-ringing']['es-cl'] = "Ringing";
$text['status-ringing']['es-mx'] = "Ringing";
$text['status-ringing']['fr-ca'] = "Ringing";
$text['status-ringing']['fr-fr'] = "Ringing";
$text['status-ringing']['he-il'] = "Ringing";
$text['status-ringing']['it-it'] = "Ringing";
$text['status-ringing']['nl-nl'] = "Ringing";
$text['status-ringing']['pl-pl'] = "Ringing";
$text['status-ringing']['pt-br'] = "Ringing";
$text['status-ringing']['pt-pt'] = "Ringing";
$text['status-ringing']['ro-ro'] = "Ringing";
$text['status-ringing']['ru-ru'] = "Ringing";
$text['status-ringing']['sv-se'] = "Ringing";
$text['status-ringing']['uk-ua'] = "Ringing";

$text['status-active']['en-us'] = "Active";
$text['status-active']['en-gb'] = "Active";
$text['status-active']['ar-eg'] = "Active";
$text['status-active']['de-at'] = "Active";
$text['status-active']['de-ch'] = "Active";
$text['status-active']['de-de'] = "Active";
$text['status-active']['el-gr'] = "Active";
$text['status-active']['es-cl'] = "Active";
$text['status-active']['es-mx'] = "Active";
$text['status-active']['fr-ca'] = "Active";
$text['status-active']['fr-fr'] = "Active";
$text['status-active']['he-il'] = "Active";
$text['status-active']['it-it'] = "Active";
$text['status-active']['nl-nl'] = "Active";
$text['status-active']['pl-pl'] = "Active";
$text['status-active']['pt-br'] = "Active";
$text['status-active']['pt-pt'] = "Active";
$text['status-active']['ro-ro'] = "Active";
$text['status-active']['ru-ru'] = "Active";
$text['status-active']['sv-se'] = "Active";
$text['status-active']['uk-ua'] = "Active";


?>